load("//buck2_macros:haskell.bzl", "haskell_library")

haskell_library(
    name = "test-lib",
    srcs = [
        "CalculatorHandler.hs",
        "EchoHandler.hs",
    ],
    deps = [
        "//lib:test-lib",
        "//lib:thrift-lib",
    ],
    packages = ["containers"],
    visibility = ["PUBLIC"],
)
