load("//buck2:haskell.bzl", "haskell_library")

haskell_library(
    name = "thrift-http",
    srcs = [
        "Thrift/Channel/HTTP.hs",
        "Thrift/Server/HTTP.hs",
    ],
    deps = [
        "//common/util:fb-util",
        "//lib:thrift-lib",
    ],
    packages = [
        "async",
        "bytestring",
        "containers",
        "http-client",
        "http-client-tls",
        "http-types",
        "network",
        "streaming-commons",
        "text",
        "utf8-string",
        "wai",
        "warp",
    ],
    visibility = ["PUBLIC"],
)
