load("//buck2:haskell.bzl", "haskell_library", "haskell_test")
load("//buck2:thrift.bzl", "thrift_library")

haskell_library(
    name = "thrift-http",
    srcs = [
        "Thrift/Channel/HTTP.hs",
        "Thrift/Server/HTTP.hs",
    ],
    deps = [
        "//hsthrift/common/util:fb-util",
        "//hsthrift/lib:thrift-lib",
    ],
    packages = [
        "async",
        "bytestring",
        "containers",
        "http-client",
        "http-client-tls",
        "http-types",
        "network",
        "streaming-commons",
        "text",
        "utf8-string",
        "wai",
        "warp",
    ],
    visibility = ["PUBLIC"],
)

_TEST_DEPS = [
    "//hsthrift/common/github:fb-stubs",
    "//hsthrift/common/util:fb-util",
    "//hsthrift/lib:test-helpers",
    "//hsthrift/lib:thrift-lib",
]

_TEST_PACKAGES = [
    "HUnit",
    "STMonadTrans",
    "aeson",
    "bytestring",
    "data-default",
    "deepseq",
    "ghc-prim",
    "hashable",
    "hspec",
    "hspec-contrib",
    "text",
    "transformers",
    "unordered-containers",
]

haskell_library(
    name = "test-lib",
    srcs = thrift_library(
        name = "test-lib",
        thrift_files = {
        # See hsthrift/lib/BUCK for why these come from there rather than
        # being generated locally - matches the Makefile re-running
        # thrift-compiler on the same hsthrift/lib .thrift files per
        # package (`-o ../http/test`) instead of sharing one generated copy.
        "//hsthrift/lib:thrift.thrift": ["Facebook/Thrift/Annotation/Thrift/Thrift/Types.hs"],
        "//hsthrift/lib:scope.thrift": ["Scope/Types.hs"],
        "//hsthrift/lib:math.thrift": [
            "Math/Types.hs",
            "Math/Adder/Client.hs",
            "Math/Adder/Service.hs",
            "Math/Calculator/Client.hs",
            "Math/Calculator/Service.hs",
        ],
        "//hsthrift/lib:echoer.thrift": [
            "Echoer/Types.hs",
            "Echoer/Echoer/Client.hs",
            "Echoer/Echoer/Service.hs",
        ],
    },
        thrift_flags = ["-I", "hsthrift/lib"],
        thrift_file_flags = {
        "//hsthrift/lib:math.thrift": ["--use-int", "-I", "hsthrift/lib"],
        "//hsthrift/lib:echoer.thrift": ["--use-int", "-I", "hsthrift/lib"],
    },
        srcs = {
        "CalculatorHandler.hs": "test/common/CalculatorHandler.hs",
        "EchoHandler.hs": "test/common/EchoHandler.hs",
    },
    ),
    deps = _TEST_DEPS,
    packages = _TEST_PACKAGES + ["containers"],
)

haskell_test(
    name = "server",
    srcs = {"ServerTest.hs": "test/ServerTest.hs"},
    main = "ServerTest",
    linker_flags = ["-threaded"],
    deps = _TEST_DEPS + [
        ":test-lib",
        ":thrift-http",
    ],
    packages = _TEST_PACKAGES + ["http-client", "http-types", "wai"],
)
