load("//buck2:haskell.bzl", "haskell_library", "haskell_test")
load("//buck2:thrift.bzl", "ANNOTATION_INCLUDES", "thrift_library")

haskell_library(
    name = "thrift-http",
    srcs = [
        "Thrift/Channel/HTTP.hs",
        "Thrift/Server/HTTP.hs",
    ],
    deps = [
        "//common/util:fb-util",
        "//lib:thrift-lib",
    ],
    packages = [
        "async",
        "bytestring",
        "containers",
        "http-client",
        "http-client-tls",
        "http-types",
        "network",
        "streaming-commons",
        "text",
        "utf8-string",
        "wai",
        "warp",
    ],
    visibility = ["PUBLIC"],
)

_TEST_DEPS = [
    "//common/github:fb-stubs",
    "//common/util:fb-util",
    "//lib:test-helpers",
    "//lib:thrift-lib",
]

_TEST_PACKAGES = [
    "HUnit",
    "STMonadTrans",
    "aeson",
    "bytestring",
    "data-default",
    "deepseq",
    "ghc-prim",
    "hashable",
    "hspec",
    "hspec-contrib",
    "text",
    "transformers",
    "unordered-containers",
]

haskell_library(
    name = "test-lib",
    srcs = thrift_library(
        name = "test-lib",
        thrift_files = {
        # Math/Echoer come from lib/ rather than being generated locally -
        # matches the Makefile re-running thrift-compiler on the same
        # hsthrift/lib .thrift files per package (`-o ../http/test`)
        # instead of sharing one generated copy. thrift.thrift/scope.thrift
        # come straight from the cell-root exports (//:thrift.thrift,
        # //:scope.thrift) that every annotation-needing target uses -
        # see buck2/thrift.bzl's ANNOTATION_INCLUDES.
        "//:thrift.thrift": ["Facebook/Thrift/Annotation/Thrift/Thrift/Types.hs"],
        "//:scope.thrift": ["Scope/Types.hs"],
        "//lib:math.thrift": [
            "Math/Types.hs",
            "Math/Adder/Client.hs",
            "Math/Adder/Service.hs",
            "Math/Calculator/Client.hs",
            "Math/Calculator/Service.hs",
        ],
        "//lib:echoer.thrift": [
            "Echoer/Types.hs",
            "Echoer/Echoer/Client.hs",
            "Echoer/Echoer/Service.hs",
        ],
    },
        thrift_flags = [],
        thrift_file_flags = {
        "//lib:math.thrift": ["--use-int"],
        "//lib:echoer.thrift": ["--use-int"],
    },
        includes = ANNOTATION_INCLUDES,
        thrift_file_includes = {
        "//lib:echoer.thrift": dict(ANNOTATION_INCLUDES, **{
            "test/if/math.thrift": "//lib:math.thrift",
        }),
    },
        srcs = {
        "CalculatorHandler.hs": "test/common/CalculatorHandler.hs",
        "EchoHandler.hs": "test/common/EchoHandler.hs",
    },
    ),
    deps = _TEST_DEPS,
    packages = _TEST_PACKAGES + ["containers"],
)

haskell_test(
    name = "server",
    srcs = {"ServerTest.hs": "test/ServerTest.hs"},
    main = "ServerTest",
    linker_flags = ["-threaded"],
    deps = _TEST_DEPS + [
        ":test-lib",
        ":thrift-http",
    ],
    packages = _TEST_PACKAGES + ["http-client", "http-types", "wai"],
)
