load("//buck2:haskell.bzl", "haskell_library")

haskell_library(
    name = "mangle",
    fb_haskell = False,
    srcs = [
        "Mangle.hs",
        "Mangle/TH.hs",
    ],
    compiler_flags = [
        "-XLambdaCase",
        "-XGeneralizedNewtypeDeriving",
    ],
    packages = [
        "containers",
        "parsec",
        "template-haskell",
    ],
    visibility = ["PUBLIC"],
)
