load("//buck2:haskell.bzl", "haskell_library")

haskell_library(
    name = "fb-stubs",
    srcs = [
        "Facebook/Init.hs",
        "TestRunner.hs",
    ],
    packages = [
        "HUnit",
    ],
    visibility = ["PUBLIC"],
)
